### ISSUE TITLE
ffmpeg无法转码，求助大佬

### ISSUE THREAD

**Issue by Crysta1PEER** [sumght-z/vits_yunzai_plugin#1]
![image](https://user-images.githubusercontent.com/91766622/199861711-a832c8d1-426a-4235-a67a-5f8f0bcea38c.png)
![image](https://user-images.githubusercontent.com/91766622/199861826-e615b348-a021-45a1-8445-e8b941407fbb.png)

使用[README.md]提供的ffmpeg，配置于 Windows Server 2012 R2
求解答，非常感谢！

**Comment by sumght-z** [comment]
这不是我提供的，你发送的是接口获取的，但这个接口噶了。

**Comment by Crysta1PEER** [comment]
> 

我是小白qwq这样的话应该怎么解决呀，感谢回复！

**Comment by sumght-z** [comment]
删掉用接口的这个js，然后git clone我的这个，用本地生成替代接口

**Comment by Crysta1PEER** [comment]
解决了，已STAR，非常感谢！
