### ISSUE TITLE
没有老版本numpy，求助大佬！

### ISSUE THREAD

**Issue by pkfbc2014** [sumght-z/vits_yunzai_plugin#2]
ERROR: Could not find a version that satisfies the requirement numpy==1.21.6 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
ERROR: No matching distribution found for numpy==1.21.6

试了很多办法，都没能安装上numpy，系统是centos 8

**Comment by sumght-z** [comment]
那就试试pip install numpy==1.3.0
或者是安装这个不用清华源。
这玩意儿版本不同，应该差距不大
也可以试试
pip install numpy --ignore-installed numpy
试试这个指令能不能安装1.21.6

**Comment by sumght-z** [comment]
我的版本甚至是1.23.3
![image](https://user-images.githubusercontent.com/54361600/199875719-242ff2e4-d075-4f44-9bfd-49bfa49440ae.png)

**Comment by pkfbc2014** [comment]
给出的办法试了，“pip install numpy==1.3.0”在python3下运行报错：
“Missing parentheses in call to 'print'. Did you mean print(" --- Could not r”
命令“pip install numpy --ignore-installed numpy”自动安装了numpy-1.19.5，怎么指定版本1.21.6呢？

**Comment by sumght-z** [comment]
先试试1.19.5能不能生成语音，能生成就不用管版本

**Comment by sumght-z** [comment]
或者是你直接把版本号去掉，pip install numpy

**Comment by pkfbc2014** [comment]
生成不了，我查看当前numpy版本还是1.20.3（原来自带的），这个1.19.5已经成功安装了，怎么设置使用1.19.5？

**Comment by sumght-z** [comment]
![image](https://user-images.githubusercontent.com/54361600/199877155-ba3f8165-38a0-41c7-aa04-a1ac1b7a54f6.png)
我这边直接安装就是1.21.6

**Comment by pkfbc2014** [comment]
我这有两个python，服务器自带的3.6和conda的3.9，现在默认用的是3.9，我先调回3.6试试

**Comment by sumght-z** [comment]
那看来得高于1.21.6这个版本，你直接去掉版本号下新的呢。python的话，我用的3.7，3.8都没问题

**Comment by pkfbc2014** [comment]
好的，我试试，先谢谢您了！

**Comment by pkfbc2014** [comment]
“pip install numpy --ignore-installed numpy”的默认镜像怎么修改呢？我看执行后自动从豆瓣上下载（笑哭），可是conda的info里都是清华镜像的路径，根本没有豆瓣的……

执行“pip install numpy --ignore-installed numpy”结果如下：
Looking in indexes: https://pypi.doubanio.com/simple
Collecting numpy
  Using cached https://pypi.doubanio.com/packages/14/32/d3fa649ad7ec0b82737b92fefd3c4dd376b0bb23730715124569f38f3a08/numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
Installing collected packages: numpy
Successfully installed numpy-1.19.5

conda info如下：
conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch

**Comment by sumght-z** [comment]
你直接pip install numpy是安装的哪个版本

**Comment by pkfbc2014** [comment]
1.19.5

**Comment by sumght-z** [comment]
能装更高的numpy版本不，我python3.7版本自动下的是1.21.6，3.8版本自动下的1.23.3

**Comment by pkfbc2014** [comment]
大佬，我安装完1.23.3了，可还是不行，还是提示“Could not find a version that satisfies the requirement numpy==1.21.6”

**Comment by sumght-z** [comment]
你安装好了后numpy是吧，那就直接把requirements.txt里numpy这一行删了，在安装环境

**Comment by pkfbc2014** [comment]
`Using legacy 'setup.py install' for librosa, since package 'wheel' is not installed.
Using legacy 'setup.py install' for jieba, since package 'wheel' is not installed.
Using legacy 'setup.py install' for audioread, since package 'wheel' is not installed.
Building wheels for collected packages: pyopenjtalk
  Building wheel for pyopenjtalk (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /bin/python3 /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpc8qyr8ca
       cwd: /tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65
  Complete output (44 lines):
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  -- Building version 0.2.0
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pyopenjtalk
  copying pyopenjtalk/version.py -> build/lib.linux-x86_64-3.6/pyopenjtalk
  copying pyopenjtalk/__init__.py -> build/lib.linux-x86_64-3.6/pyopenjtalk
  creating build/lib.linux-x86_64-3.6/pyopenjtalk/htsvoice
  copying pyopenjtalk/htsvoice/README.md -> build/lib.linux-x86_64-3.6/pyopenjtalk/htsvoice
  copying pyopenjtalk/htsvoice/mei_normal.htsvoice -> build/lib.linux-x86_64-3.6/pyopenjtalk/htsvoice
  copying pyopenjtalk/htsvoice/LICENSE_mei_normal.htsvoice -> build/lib.linux-x86_64-3.6/pyopenjtalk/htsvoice
  running build_ext
  skipping 'pyopenjtalk/openjtalk.cpp' Cython extension (up-to-date)
  skipping 'pyopenjtalk/htsengine.cpp' Cython extension (up-to-date)
  building 'pyopenjtalk.openjtalk' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/pyopenjtalk
  creating build/temp.linux-x86_64-3.6/lib
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/jpcommon
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/mecab
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/mecab/src
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/mecab2njd
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/njd
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/njd2jpcommon
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/njd_set_accent_phrase
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/njd_set_accent_type
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/njd_set_digit
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/njd_set_long_vowel
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/njd_set_pronunciation
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/njd_set_unvoiced_vowel
  creating build/temp.linux-x86_64-3.6/lib/open_jtalk/src/text2mecab
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_CONFIG_H -DDIC_VERSION=102 -DMECAB_DEFAULT_RC="dummy" -DPACKAGE="open_jtalk" -DVERSION="1.10" -DCHARSET_UTF_8 -I/tmp/pip-build-env-wujax6lh/overlay/lib64/python3.6/site-packages/numpy/core/include -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/jpcommon -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/mecab/src -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/mecab2njd -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/njd -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/njd2jpcommon -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/njd_set_accent_phrase -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/njd_set_accent_type -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/njd_set_digit -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/njd_set_long_vowel -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/njd_set_pronunciation -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/njd_set_unvoiced_vowel -I/tmp/pip-install-eva2p_td/pyopenjtalk_a7414f06b3d14a069173260c2f361f65/lib/open_jtalk/src/text2mecab -I/usr/include/python3.6m -c pyopenjtalk/openjtalk.cpp -o build/temp.linux-x86_64-3.6/pyopenjtalk/openjtalk.o
  pyopenjtalk/openjtalk.cpp:6:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  /tmp/pip-build-env-wujax6lh/overlay/lib/python3.6/site-packages/setuptools/dist.py:726: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
    % (opt, underscore_opt)
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyopenjtalk
Failed to build pyopenjtalk
ERROR: Could not build wheels for pyopenjtalk, which is required to install pyproject.toml-based projects
`

请问Python.h可以在什么地方找到呢？

**Comment by sumght-z** [comment]
openjtalk的问题，这个的linux和win安装不同，linux可以直接安装
win需要看一下这个视频https://www.bilibili.com/video/BV13t4y1V7DV/?spm_id_from=333.337.search-card.all.click

**Comment by pkfbc2014** [comment]
诶，我的是linux不是win

**Comment by sumght-z** [comment]
那你直接pip install pyopenjtalk试试
如果安装好了，就去txt把这一行安装删掉
