### ISSUE TITLE
大佬,我的原神语音没有生成,但是其它都行,也没有报错日志

### ISSUE THREAD

**Issue by WaveCai** [sumght-z/vits_yunzai_plugin#3]
![image](https://user-images.githubusercontent.com/49021184/199905244-6c209325-bf4d-4308-9f53-52076355798f.png)
![image](https://user-images.githubusercontent.com/49021184/199908847-c8e132bd-275c-4afd-a096-f02c84c5a7bb.png)

**Comment by sumght-z** [comment]
崩三的能说是吧

**Comment by WaveCai** [comment]
是的,像星爷这些也是可以的
![image](https://user-images.githubusercontent.com/49021184/199910172-7405f6a0-487e-47c6-8004-b63224343358.png)
![image](https://user-images.githubusercontent.com/49021184/199910257-b2f5fe78-f936-4a29-8800-865e95c90c8e.png)

**Comment by sumght-z** [comment]
我测试了一下，我这边跑没问题，你尝试重启一下。或者是发送后等一下。因为是异步的cpu推演。你云服务器单核的话压力挺大的，如果需要cuda版本可以等我更新之后的版本。

**Comment by WaveCai** [comment]
我用的自己的那种电脑来运行机器人的，发送后等待很久机器人也不会回复；看了下任务管理器硬盘有读取速度，说明ys.pth读取成功了，Python这块我不是很熟，想打印你的输出不会弄，折腾蛮久还是不行，我还是等你这边cuda版本吧
![image](https://user-images.githubusercontent.com/49021184/199918742-c82fca9c-02f7-45f1-8f97-e912c6e83533.png)

**Comment by sumght-z** [comment]
那你可以试试把插件删了，重新git clone一下。重装没准就能解决，你能发送崩三的，证明环境肯定没问题

**Comment by WaveCai** [comment]
插件试过删除过重新配置了,就原神不行,我贴上/vits/monotonic_align这里的日志供大佬这边参考下
Compiling core.pyx because it changed.
[1/1] Cythonizing core.pyx
C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: D:\Code\Yunzai-Bot\plugins\vits-yunzai-Plugin\vits\monotonic_align\core.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'monotonic_align.core' extension
creating build\temp.win-amd64-cpython-37
creating build\temp.win-amd64-cpython-37\Release
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python37\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python37\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /Tccore.c /Fobuild\temp.win-amd64-cpython-37\Release\core.obj
core.c
core.c(2362): warning C4244: “=”: 从“Py_ssize_t”转换到“int”，可能丢失数据
creating D:\Code\Yunzai-Bot\plugins\vits-yunzai-Plugin\vits\monotonic_align\build\lib.win-amd64-cpython-37
creating D:\Code\Yunzai-Bot\plugins\vits-yunzai-Plugin\vits\monotonic_align\build\lib.win-amd64-cpython-37\monotonic_align
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\Administrator\AppData\Local\Programs\Python\Python37\libs /LIBPATH:C:\Users\Administrator\AppData\Local\Programs\Python\Python37 /LIBPATH:C:\Users\Administrator\AppData\Local\Programs\Python\Python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64" /EXPORT:PyInit_core build\temp.win-amd64-cpython-37\Release\core.obj /OUT:build\lib.win-amd64-cpython-37\monotonic_align\core.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-37\Release\core.cp37-win_amd64.lib
  正在创建库 build\temp.win-amd64-cpython-37\Release\core.cp37-win_amd64.lib 和对象 build\temp.win-amd64-cpython-37\Release\core.cp37-win_amd64.exp
正在生成代码
已完成代码的生成
copying build\lib.win-amd64-cpython-37\monotonic_align\core.cp37-win_amd64.pyd -> monotonic_align

**Comment by sumght-z** [comment]
这个日志没有问题，如果你怕有问题，你可以把bh3的monotonic_align文件夹复制给原神这边的，是通用的。我git clone了这个库的，都能生成。emmmmmm，看起来没问题啊

**Comment by sumght-z** [comment]
好了，更新完成，修复了原神不发送的bug

**Comment by sumght-z** [comment]
好了，更新完成，修复了原神不发送的bug

**Comment by WaveCai** [comment]
我测试已经正常了,感谢大佬
